name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:

      - name: Debug token
        run: |
          if [ -z "${{ secrets.METRICS_TOKEN }}" ]; then
            echo "TOKEN KOSONG"
            exit 1
          else
            echo "TOKEN ADA"
          fi

      - uses: lowlighter/metrics@latest
        with:
          user: Putrazaubdillah
          token: ${{ secrets.METRICS_TOKEN }}
